# Tell Nixpacks how to build the application
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["npm run build"]

# Tell Nixpacks how to start the application
[start]
cmd = "npx serve -s dist -l 80"
