# ⚠️  REFERENCE ONLY - DO NOT DEPLOY THIS FILE ⚠️
# This file shows the required configuration for file storage
# Copy ONLY the file storage settings to your existing Dockploy apps
# DO NOT replace your existing deployment with this file!

version: "3.8"

services:
    # Your backend server
    beout-server:
        build: ./server
        container_name: beout-server
        ports:
            - "3000:3000"
        environment:
            # Database connection
            - DATABASE_URL=${DATABASE_URL}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}

            # File storage configuration
            - UPLOAD_PATH=/app/uploads
            - PUBLIC_FILES_URL=https://yourdomain.com/uploads
            - MAX_FILE_SIZE=10485760
            - ALLOWED_IMAGE_TYPES=image/jpeg,image/png,image/webp,image/gif
            - ALLOWED_DOCUMENT_TYPES=application/pdf,application/msword

            # Other environment variables
            - JWT_SECRET=${JWT_SECRET}
            - NODE_ENV=production
        volumes:
            # CRITICAL: This volume persists files across container rebuilds
            - beout_uploads:/app/uploads
        restart: unless-stopped
        networks:
            - beout-network

    # Your frontend clients
    beout-client:
        build: ./client
        container_name: beout-client
        ports:
            - "5173:80"
        environment:
            - VITE_API_BASE_URL=https://api.yourdomain.com
        restart: unless-stopped
        networks:
            - beout-network

    beout-admin:
        build: ./admin-client
        container_name: beout-admin
        ports:
            - "5174:80"
        environment:
            - VITE_API_BASE_URL=https://api.yourdomain.com
        restart: unless-stopped
        networks:
            - beout-network

    beout-organizer:
        build: ./organizer-client
        container_name: beout-organizer
        ports:
            - "5175:80"
        environment:
            - VITE_API_BASE_URL=https://api.yourdomain.com
        restart: unless-stopped
        networks:
            - beout-network

    # Nginx for file serving and reverse proxy
    nginx:
        image: nginx:alpine
        container_name: beout-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            # Mount the same uploads volume for serving files
            - beout_uploads:/var/www/uploads:ro
            - ./ssl:/etc/nginx/ssl
        depends_on:
            - beout-server
        restart: unless-stopped
        networks:
            - beout-network

# CRITICAL: Define the persistent volume
volumes:
    beout_uploads:
        driver: local
        # This volume will persist on the host at:
        # /var/lib/docker/volumes/beout_uploads/_data/

networks:
    beout-network:
        driver: bridge
