name: Client Test and Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'client/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'client/**'
      - 'package.json'
      - 'package-lock.json'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build-client:
    name: Test and Build Client (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Test client
      run: npm run test --workspace=client --if-present

    - name: Build client for web
      run: npm run build --workspace=client
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}

    - name: Upload web build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client-web-build
        path: client/build/
        retention-days: 7
